java:
  image: 'https://hmctspublic.azurecr.io/ia/case-api:latest'
  applicationPort: 8090
  aadIdentityName: ia
  environment:
    PROF_REF_DATA_URL: "http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  keyVaults:
    ia:
      secrets:
        - case-documents-api-url
        - case-notifications-api-url
        - docmosis-enabled
        - em-stitching-enabled
        - submit-hearing-requirements-enabled
        - system-username
        - system-password
        - idam-client-id
        - idam-secret
        - idam-redirect-uri
        - s2s-secret
        - s2s-microservice
        - ccd-url
        - ccd-gw-url
        - dm-url
        - idam-url
        - s2s-url
        - prof-ref-data-url
        - docmosis-enabled
        - em-stitching-enabled
        - AppInsightsInstrumentationKey